name: Building Security Pipeline

on: 
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_TAR: ${{ github.sha }}.tar

jobs:
  build:
    name: Build artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t ${{ env.IMAGE_TAG }} ./juice-shop
          docker save ${{ env.IMAGE_TAG }} > ${{ env.IMAGE_TAR }}

      - name: Upload Docker Image artifact
        uses: actions/upload-artifact@v4
        with: 
          name: docker-image
          path: ${{ env.IMAGE_TAR }}