name: Building Security Pipeline

on: 
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

env:
  IMAGE_TAG: ${{ github.sha }}
  IMAGE_TAR: ${{ github.sha }}.tar

jobs:
  # Detect Secret
  detect-secrets:
    name: Detect Secret
    runs-on: ubuntu-latest
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'
      
      - name: Install detect-secrets
        run: pip install detect-secrets

      - name: Verify baseline and setup
        run: |
          if [ ! -f ".secrets.baseline" ]; then
            echo "::error::Baseline file .secrets.baseline missing! Run detect-secrets scan > .secrets.baseline locally first."
            exit 1
          fi
          mkdir -p reports

      # compare latest commit file
      - name: Run detect-secrets scan
        run: | 
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            BASE_REF="${{ github.event.pull_request.base.sha }}"
          else
            if [ "${{ github.event.before }}" = "0000000000000000000000000000000000000000" ] || [ -z "${{ github.event.before }}" ]; then
              BASE_REF=$(git rev-parse HEAD~1 2>/dev/null || echo "")
            else
              BASE_REF="${{ github.event.before }}""
            fi
          fi

          echo "Base Commit: ${BASE_REF}"
          echo "Current Commit: ${{ github.sha }}"

          if [ -n "$BASE_REF" ]; then
            CHANGED_FILES=$(git diff --name-only --diff-filter=d "$BASE_REF" "${{ github.sha }}")
          else
            CHANGED_FILES=$(git ls-files)
          fi

          echo "Changed files to scan:"
          echo "$CHANGED_FILES"

          if [ -n "$CHANGED_FILES" ]; then
            echo "$CHANGED_FILES" | xargs detect-secrets-hook --baseline .secrets.baseline 2>&1 | tee reports/detect-secrets-report.txt
          else
            echo "No changed files detected to scan."
          fi
          
      - name: Upload Detect-Secrets Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: detect-secrets-report
          path: reports/detect-secrets-report.txt

  sast:
    name: Code & Dockerfile check
    runs-on: ubuntu-latest
    needs: [detect-secrets]
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Setup Tools & Workspace
        run: | 
          mkdir -p reports
          pip install semgrep

      - name: Run Hadolint and Generate Reports
        continue-on-error: true
        run: |
          mkdir -p reports
          docker run --rm -i hadolint/hadolint:latest hadolint --no-fail - < juice-shop/Dockerfile > reports/hadolint-report.txt
          docker run --rm -i hadolint/hadolint:latest hadolint --failure-threshold warning -f sonarqube - < juice-shop/Dockerfile > reports/hadolint-report.json || true

      - name: Run Semgrep
        continue-on-error: true
        run: | 
          pip install semgrep
          semgrep scan --config auto --json -o reports/semgrep-report.json ./juice-shop || true
          semgrep scan --config auto ./juice-shop > reports/semgrep-report.txt || true

      - name: Reporting
        if: always()
        run: | 
          if [ -s "reports/hadolint-report.txt" ]; then
            cat reports/hadolint-report.txt
          fi

          if [ -s "reports/njsscan-report.json" ]; then
            cat reports/njsscan-report.json
          fi

          if [ -s "reports/semgrep-report.json" ]; then
            cat reports/semgrep-report.json
          fi
      
      - name: Upload Hadolint Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: hadoline-report
          path: | 
            reports/hadolint-report.txt
            reports/njsscan-report.json
            reports/semgrep-report.json

  sonarqube:
    runs-on: ubuntu-latest
    needs: [detect-secrets]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v8.2.2
        with:
          args: >
            -Dsonar.projectKey=devsecops-practice
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.sources=.
            -Dsonar.exclusions=reports/**,node_modules/**,frontend/dist/**,**/*.spec.ts
            -Dsonar.qulitygate.wait=true 
        env: 
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  # Build Image
  build:
    name: Build artifact
    runs-on: ubuntu-latest
    needs: [detect-secrets, sast, sonarqube]
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build docker image
        run: |
          DOCKER_BUILDKIT=1 docker build -t ${{ env.IMAGE_TAG }} ./juice-shop
          docker save ${{ env.IMAGE_TAG }} > ${{ env.IMAGE_TAR }}

      - name: Upload Docker Image artifact
        uses: actions/upload-artifact@v4
        with: 
          name: docker-image
          path: ${{ env.IMAGE_TAR }}

  # SCA Dependency check
  dependency-check:
    name: Run Dependency Check
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      security-events: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '24'

      - name: Install dependencies (Root and Frontend)
        run: | 
          cd juice-shop
          npm install
          cd frontend
          npm install --legacy-peer-deps
      
      - name: Create report directory
        run: mkdir -p reports

      - name: OWASP Dependency Check
        uses: dependency-check/Dependency-Check_Action@main
        continue-on-error: true
        env:
          npm_config_legacy_peer_deps: true
        #env:
          # Prevent Rate Limited
        #  NVD_API_KEY: ${{ secrets.NVD_API_KEY }}
        with:
          project: 'devsecops-practice'
          path: './juice-shop'
          format: 'HTML'
          out: 'reports'
          args: >
            --failOnCVSS 7
            --enableExperimental
            --exclude "**/test/**"
            --exclude "**/*.zip"
            --exclude "**/*.exe"
            --exclude "**/build/**"
      
      - name: Upload Dependency Check Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: dependencycheck-report
          path: | 
            reports/dependencycheck-report.html
    
  # Container scan
  trivy:
    name: Container Scan with Trivy
    runs-on: ubuntu-latest
    needs: [build]
    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i ${{ env.IMAGE_TAR }}

      - name: Run Trivy vulnerability scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_TAG }}' 
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

      - name: Generate Trivy Report
        if: always()
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_TAG }}'
          format: 'json'
          output: 'trivy-report.json'

      - name: Upload Trivy Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: trivy-report
          path: trivy-report.json

      - name: Trivy GateKeeper
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: '${{ env.IMAGE_TAG }}'
          format: 'table'
          exit-code: '1'
          ignore-unfixed: true
          vuln-type: 'os,library'
          severity: 'CRITICAL,HIGH'

  dast:
    name: Run ZAP DAST Scan
    runs-on: ubuntu-latest
    needs: [build]

    permissions:
      contents: read
      issues: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download docker image artifact
        uses: actions/download-artifact@v4
        with:
          name: docker-image

      - name: Load Docker Image
        run: docker load -i ${{ env.IMAGE_TAR }}

      - name: Run Juice Shop Container
        run: |
          docker run --rm -d --network host --name juice-shop ${{ env.IMAGE_TAG }}

          echo "Waiting for Juice Shop to start on port 3000"
          until curl -s http://localhost:3000 > /dev/null; do
            sleep 2
          done 
          echo "Juice Shop is UP and running!"
        

      - name: Run ZAP Baseline Scan
        run: |
          mkdir -p reports
          docker run --rm --network host -v $(pwd):/zap/wrk/:rw \
            zaproxy/zap-stable zap-baseline.py \
            -t http://localhost:3000 \
            -r report_html.html \
            -w report_md.md \
            -I

      - name: Upload DAST Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-dast-report
          path: |
            reports/zap_report.html
            reports/zap_report.md